import subprocess

import pytest

config1_domains = ["tzxnmjybkjytxrge.com",
                   "wrovtrqqtperjj.com",
                   "csbenuubveeistri.com",
                   "nxzfpdiecpegwpb4l.com",
                   "pdpilfwaqsr5.com",
                   "wahcabnfsdoqftwd1r.com",
                   "evsnfhkvtwai30.com",
                   "tjqlcsewgnsaeawdj2.com",
                   "bkiyjtzycuhopg.com",
                   "yahgbihifepqb.com",
                   "zmdddkboasql.com",
                   "ijcpgtkkaeryqd.com",
                   "innganvmcvymbwog.com",
                   "hgwtulyiyzm6.com",
                   "xmfskhzszdwxafem2x.com",
                   "dcexrwjvgnzcphs.com",
                   "fqdqoevaqzaq5l.com",
                   "fdqqfsdedxyeuackn5.com",
                   "rchahcisdyaar54.com",
                   "pugpzwvkxwqgs.com",
                   "wmsbscuhjalqvelce.com",
                   "ermxuwiipz8n.com",
                   "vhlidjocyqkzlwjg4.com",
                   "yovrnjtgsmykyf.com",
                   "vraxdeoszjyt5.com",
                   "jlnfxqhwalzt.com",
                   "yuzwsltpdhswnkn.com",
                   "jjjchdeoyoywtuhi.com"]

config2_domains = ["pansmstagppxan.com",
                   "gfxygzqavvbqgqquxu.com",
                   "wrqxmjiipqaccdg.com",
                   "bovxtdkwewxvki.com",
                   "hnfyrpmeewyxliimkp.com",
                   "mojeefeypksck.com",
                   "axrfkkpyqedd2.com",
                   "krjaosssghknpop7e.com",
                   "tqutdqyepxbxvfe.com",
                   "tucnkahbvtidndvll.com",
                   "tmrhkgfybdyeuclu0z.com",
                   "xjayztxvskpxtjx.com",
                   "hbmykijiuaam5.com",
                   "vwyjgnpuhwoylk2j.com",
                   "ebpptpugrkjifmimo6.com",
                   "gliafjovbumvu2.com",
                   "fwptryqcrsbqwkck.com",
                   "qudkebwnpkufjpefc.com",
                   "whsclzbvmvsusyhauk.com",
                   "slwxcjptwaqqpui5p.com",
                   "zdsutwmsjie9.com",
                   "qkcgcvmqgphrs.com"]

config3_domains = ["oungflmaviuh.com",
                   "gvocwssqnxqc6m.com",
                   "vnijkfyhrispjnvzh9.com",
                   "debtpjznzrsplq7.com",
                   "xjhxohepltppnv.com",
                   "pjthfqiljwhzl.com",
                   "tlcujjabwtqadswp5w.com",
                   "ucbmulnexefgqws.com",
                   "cqlgrlyzfbxuhuk.com",
                   "vlrcbvoaxgiyo33.com",
                   "jkoaznelgjmz.com",
                   "ezuelpbwpapz.com",
                   "bqidpkgmbjsqktipst.com",
                   "zkpqcgyzumsjdzoqj.com",
                   "kungbirqasyquomlss.com",
                   "vjtgddeqjxwd.com",
                   "nyowzvycqdquhifut.com",
                   "eaigihezsyeiuif5o.com",
                   "wppitdeosxwp.com",
                   "juakjbdadkeef.com",
                   "qjzjnqlawxrmsssch.com",
                   "ruytjapmstmuaevyzk.com",
                   "sgxrmfuakwwdgj.com",
                   "nvmkraqeinwrq6d.com",
                   "zqknlkfixizerkj6.com",
                   "hzpbeyzhjvuwld9.com",
                   "vdcrpiaofzwjjaoe3l.com",
                   "hzttizvwjnfxlf6i.com"]

config4_domains = ["koocslenjnojra6s.com",
                   "yjhtcarkkwcqjy.com",
                   "keyiiokltxlzv5q.com",
                   "arqduqjglqhzx.com",
                   "fsdccdwliojyx9f.com",
                   "cawevaxdsvwu.com",
                   "uewzytotknoft.com",
                   "livmhlkayepcflsjis.com",
                   "dyuvbpczeiwejh.com",
                   "uyrmmvkhjzouavdzlm.com",
                   "opmytadbbcnvngmke.com",
                   "ejylqzfbintpvhs.com",
                   "chwbubwwfoyerbst8.com",
                   "tlambriqgvzireloy0.com",
                   "dddosmufjueotsa.com",
                   "ulilnrluyycwjs.com",
                   "cpjidiflbjndvspzj.com",
                   "bwwpnadywmr5.com",
                   "eznivbahxnamezo.com",
                   "xwynytrlgzsdnhk.com",
                   "nfvxxjfqurnmgc.com",
                   "hvbgrbcwmysvaw.com",
                   "teqqllqiokvmjzymt.com",
                   "doeowhfqhrljnbh1.com",
                   "hccrjcuumpyf8s.com",
                   "sexpykakihtlx.com",
                   "arkalqtwkzpkac.com",
                   "aetozcdtkkkvxbhac9.com"]

config5_domains = ["cxynbktpncplgxk.com",
                   "rsbgrunupykopwl6l.com",
                   "fyakcomzxeiu.com",
                   "nqbuacdgknokuizs.com",
                   "qvmrzreaplonbz.com",
                   "pungedmvbpwb5i.com",
                   "lhnqldaooggegz.com",
                   "wxpievhychf9.com",
                   "fqyewtrrtudflpha7.com",
                   "zpgkwhvbxbgpqoaun.com",
                   "yvoogcyvffp0b.com",
                   "hmmmljrwko2v.com",
                   "yzcbsibhhxjgylbldp.com",
                   "glyxdxforuaaebxun5.com",
                   "rbrsgzefsd49.com",
                   "jppwzhkguuiac0.com",
                   "flaoxwmnpzisien2.com",
                   "cofifairtehd.com",
                   "zuoxrgpjunruv1g.com",
                   "hsaojspkpkrtf.com",
                   "vnvinqktbkqmgqop2.com",
                   "wdoztkuqqszpmcu7.com",
                   "aoxwpokddpuladggn.com",
                   "labeerhnuyvbs1.com",
                   "uarihgyqjclvyst9h.com",
                   "roovcgytpljife.com",
                   "dqzexlyczqf2q.com",
                   "shdifjuumngp54.com"]

config6_domains = ["nwaslcusqndmdllsa6.com",
                   "bqeglpoirqi0h.com",
                   "jnwebvqzhwrlla7m.com",
                   "mouiwncazbc6.com",
                   "mdupodcvsunn.com",
                   "pmsdktdcijtdrstyr.com",
                   "nhjdssbyymvkolaue5.com",
                   "gxbmjruwurrx.com",
                   "aqnmylzgycqokmyh2h.com",
                   "lpfoxqcdsdotpnr.com",
                   "mpdjmcusvjxchy.com",
                   "qnxiaouwohqfsu59.com",
                   "ebhtccjbriyujaab.com",
                   "kiiggzxeeofium.com",
                   "nskgmfsmacnotha.com",
                   "vgipzlwtwrczqrd.com",
                   "qahelfwyfjqvmjsg1s.com",
                   "vhjnzrkglefskg.com",
                   "phdaicgkreps7n.com",
                   "fsedxzlyswzbedizud.com",
                   "yjhqdluqbjzus.com",
                   "mfiuqkyfwtlsqh4.com"]

config7_domains = ["evsvfftykpqhnk.com",
                   "skhsetzruhrrpckyu.com",
                   "fywttqimjc6u.com",
                   "fbgrxexrhjfobv.com",
                   "endgobmokyfsatiq5l.com",
                   "twzhycfitukplgrd.com",
                   "rchmgbyemfyfwchr.com",
                   "mmumigfxwhbr81.com",
                   "dvfospgnlaj9.com",
                   "vlaaoawnxhltr.com",
                   "zkyrrvbdvlzcklnvy.com",
                   "gxwjqafxfgni.com",
                   "gjyllaokuahiyg.com",
                   "nlmljgiujf02.com",
                   "zmzcfwzwdsbqrqup.com",
                   "sxytojwrupu59.com",
                   "hiwdvrausibeuwp7.com",
                   "pwtohreuxomssn.com",
                   "myjwzhqtnryqlcxe.com",
                   "tbgbqvjpfsoqxnb65.com",
                   "yxicmwfvgqxgkgvay.com",
                   "ffbvktelirakdhrvf4.com",
                   "skwcxqzuixeglzwnj.com",
                   "ytjuhvtehhgc.com",
                   "bdeyjmcianqbzfne21.com",
                   "bifsrueyhqwncr.com",
                   "spdsguqkcjwssakd4.com",
                   "kqirfvmhfukpxxtgvu.com"]

config_list = [config1_domains,
               config2_domains,
               config3_domains,
               config4_domains,
               config5_domains,
               config6_domains,
               config7_domains]

ids = ["config1_domains",
       "config2_domains",
       "config3_domains",
       "config4_domains",
       "config5_domains",
       "config6_domains",
       "config7_domains"]


@pytest.fixture(scope="class")
def bedep_domains():
    cmd = ["bedep_dga", "--start", "2020-08-06", "--end", "2020-08-06"]
    output = subprocess.check_output(cmd, universal_newlines=True)
    return output


class Test_all_configs_return_expected_domains:
    @pytest.mark.parametrize("config_domains", config_list, ids=ids)
    def test_all_configs(self, bedep_domains, config_domains):
        assert all(domain in bedep_domains for domain in config_domains)
