name: pytest
on:
  push:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Pytest and Coverage
        run: |
          pip install pytest pytest-cov 
          pytest --cov=tests
